apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: amazon-prime:/Service:default/prime-app
  labels:
    app: prime-app
  name: prime-app
  namespace: default
spec:
  ports:
    - nodePort: 30001
      port: 3000
      targetPort: 3000
  selector:
    app: prime-app
  type: NodePort
